services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 8888:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}

networks:
  app_network:
    driver: bridge
volumes:
  postgres_data:




