server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:8888/${NAME_DB}"
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  #liquibase:
   # enabled: false
    #change-log: db/changelog/db.changelog-master.yaml
  flyway:
    user: admin
    password: secret
    schemas: cloudFileService

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: USER-SERVICE
