server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}"
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  liquibase:
    enabled: true
    change-log: db/changelog.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: USER-SERVICE

  minio:
    url: http://localhost:9001
    bucket: ${MINIO_BUCKET_NAME}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    port: 9000
token:
  signing:
    key: ${TOKEN_SIGNING_KEY}

